### PR TITLE
fix: don't display buy new stamp button when already in process of buying one

### PR DESCRIPTION
**Pull request by vojtechsimetka**
Screenshot 2022-06-21 at 12 07 02

### CODE REVIEW

**Comment by AuHau** [comment]
Honestly, not sure why to have it disabled? Maybe the user wants to buy a new postage batch with the upload?

**Comment by bee-worker** [comment]
## 🐝 PR preview in Swarm

**Preview URL:** https://bah5acgza2l3tcgt3fh66rcr3a4hq7o3anslkolw6bzm7x5mv2j7zb23kwphq.bzz.link
**Swarm Hash:** `d2f7311a7b29fde88a3b070f0fbb606c96a72ede0e59fbf595d27f90eb6ab3cf`
**Commit Hash:** ffa2eeb05d6fa53cda55fc4da6063c2acfbb6928
**Commit Message:** fix: don't display buy new stamp button when already in process of buying one

**Comment by vojtechsimetka** [comment]
> Honestly, not sure why to have it disabled? Maybe the user wants to buy a new postage batch with the upload?

And that is still there. We only don't show that button when the user already is in the process of buying stamp.
Screenshot 2022-06-21 at 12 26 47
 
 
 This is what the PR solves (reported by david). If we have no stamp on the node, it automatically goes to the "buy new stamp" flow.
Screenshot 2022-06-21 at 10 33 24

**Review by AuHau — APPROVED** [review]

**Comment by david-swarm** [comment]
it should be replaced by a button saying "use existing stamp"

**Pull request merged**
