### PR TITLE
ci: migrate to swarm-actions for PR previews

### PR DESCRIPTION
**Pull request by vojtechsimetka**

### CODE REVIEW

**Comment by bee-worker** [comment]
## 🐝 PR preview in Swarm

**Preview URL:** https://bah5acgzaseq4t2gip5u4txuq36tihozxq6z5pvvnczact5zmf2zcpgtjffka.bzz.link
**Swarm Hash:** `9121c9e8c87f69c9de90dfa683bb3787b3d7d6ad164029f72c2eb2279a692954`
**Commit Hash:** 098fe081f3fd580f6494dca80e8b5cf25f9f12cc
**Commit Message:** ci: migrate to swarm-actions for PR previews

**Review by Jacquelinevv0693 — APPROVED** [review]

**Comment by filoozom** [comment]
The `Upload to Testnet` action actually failed with `Error: Request Entity Too Large`. Strange, as the workflow in itself didn't fail. I guess that's a bug in [swarm-actions](https://github.com/ethersphere/swarm-actions).

Does the testnet gateway limit the uploads more than the mainnet one?

**Comment by vojtechsimetka** [comment]
Yes. On mainnet we have unlimited node, for testnet we have 10 mb limit. This is actually expected behavior because we have this trstnet upload as optional (continue on error). The problem with GH actions is that there is no such thing as optional.

we will probably increase the testnet limit soon.

**Comment by vojtechsimetka** [comment]
@Cafe137 can we get this merged?

**Review by Cafe137 — APPROVED** [review]

**Pull request merged**
