### PR TITLE
feat: add electron build

### PR DESCRIPTION
**Pull request by Cafe137**

### CODE REVIEW

**Comment by vojtechsimetka** [comment]
Thanks @Cafe137 for this!

Could you limit the size of the app when opening not to be full screen? Each time I open it again on macOS it covers my whole screen.

This is the warning that when building. Not sure if anything can be done:
`
```
> @ethersphere/bee-dashboard@0.5.0 dist:macos
> npm run build && electron-builder build --macos --x64 --publish never


> @ethersphere/bee-dashboard@0.5.0 build
> react-scripts build

(node:73302) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at ./bee-status/node_modules/postcss-safe-parser/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Compiled successfully.
```

**Comment by vojtechsimetka** [comment]
Also please add the `dist` folder to `.gitignore`

**Comment by Cafe137** [comment]
> Also please add the `dist` folder to `.gitignore`

@vojtechsimetka Hmm that's odd, I added `/dist`, is it not working for you?

**Comment by vojtechsimetka** [comment]
I'm going to close this one :)

**Pull request closed without merging**
