### PR TITLE
feat: add metadata and preview

### PR DESCRIPTION
**Pull request by vojtechsimetka**
This includes #291, I would have to extract that commit out which seemed a lot of unnecessary work. I can rebase when it gets merged.

### CODE REVIEW

**Comment by bee-worker** [comment]
## 🐝 PR preview in Swarm

**Preview URL:** https://bah5acgzawiy74zqcm27335nhs3al7khyo57xsfzuizpwmlrgaj3ojnynzyoq.bzz.link
**Swarm Hash:** `b231fe660266bfbdf5a796c0bfa8f8777f791734465f662e260276e4b70dce1d`
**Commit Hash:** 4a6cda14f9bb9d54592d53cbdb164b6fb62b3d39
**Commit Message:** feat: add metadata and preview on download

**Comment by Cafe137** [comment]
The code LGTM, however I get an error when uploading websites.

Bee Dashboard error:

`Error uploading: Internal Server Error: could not store directory`

Bee error:

`bzz upload dir: store dir`

When I switch back to `master`, the issue disappears.

Tested with `1.4.1-238867f1-dirty` `bee dev`

**Comment by vojtechsimetka** [comment]
So the issue is with supplying the `indexDocument` here https://github.com/ethersphere/bee-dashboard/pull/292/files#diff-34cbf5f73b5317ec1db6c2fe17490f90e3462deec2b953b9bc546fd98e2bc2deR104

The response from bee is quite cryptic:
```
time="2022-01-24T18:58:45Z" level=debug msg="bzz upload dir: store dir err: index document suffix must not include slash character"
time="2022-01-24T18:58:45Z" level=error msg="bzz upload dir: store dir"
```

but there seems to be an issue about it already https://github.com/ethersphere/bee/issues/2661

The files that I am testing is the `build` folder of the `bee-dashboard` with the `.swarmmetadata` file included (but omitting it does not resolve the issue). The index document is set to `build/index.html`:
```
.swarmmetadata
build/favicon.ico
build/index.html
build/serve.json
build/asset-manifest.json
build/static/css/main.59b0af6f.chunk.css.map
build/static/css/main.59b0af6f.chunk.css
build/static/js/runtime-main.1e0e2465.js
build/static/js/2.44e3e3b9.chunk.js.map
build/static/js/3.e2eeb6c0.chunk.js.map
build/static/js/3.e2eeb6c0.chunk.js
build/static/js/2.44e3e3b9.chunk.js
build/static/js/2.44e3e3b9.chunk.js.LICENSE.txt
build/static/js/main.16a7a19c.chunk.js
build/static/js/main.16a7a19c.chunk.js.map
build/static/js/runtime-main.1e0e2465.js.map
build/static/media/WorkSans-Regular.1cafe0d5.ttf
build/static/media/WorkSans-VariableFont_wght.7655b042.ttf
build/static/media/IBMPlexMonoregular.bee53c8c.ttf
build/static/media/logo.3d1155fe.svg
build/static/media/WorkSans-Light.485b5eb0.ttf
build/static/media/IBMPlexMono500.a79f8a2f.ttf
build/static/media/WorkSans-SemiBold.3cdc6ded.ttf
build/static/media/WorkSans-Medium.d7a97380.ttf
build/static/media/WorkSans-Italic-VariableFont_wght.613db76c.ttf
build/static/media/IBMPlexMono600.0331e38c.ttf
build/manifest.json
build/robots.txt
```

**Comment by agazso** [comment]
I think the proposed solution is good and it's not modify the content in a meaningful way. The expectation with the file selector is that you 1) either select a folder for uploading its content or 2) to go to a folder and select all files in it.

Furthermore I would argue that adding the metadata modifies more the uploaded content in an unexpected way, but that should be another discussion :)

**Comment by vojtechsimetka** [comment]
Thanks for the feedback. I agree. In the end there is actually a middle ground. Only websites in a 1 level deep folder structure are detected and flattened. Downloading from `gateway` or `bee-dashboard` actually puts the files back in the folder (within the zip file).

**Comment by Cafe137** [comment]
I can upload websites now, however they appear as folders when accessing. On it.

```
count: 3
hash: "ed73af53e884bd7f09af02d78794560237f53eb1ccfbdc734d0520e202ca597e"
isWebsite: false
name: "test-website"
size: 390098
type: "folder"
```

**Comment by Cafe137** [comment]
In `Share.tsx` there seems to be a race condition.

When I upload webites, they appear as folders initially, this is a bug.

However, when hot reload triggers a refresh on the same Share page, it correctly switches from Folder to Website. This never seems to happen on initial load and render of the page though.

**Comment by vojtechsimetka** [comment]
@Cafe137 thanks a lot for the fixes. From my end it is good to go.

**Review by Cafe137 — APPROVED** [review]

**Pull request merged**
