### PR TITLE
feat: add map with peers to info page

### PR DESCRIPTION
**Pull request by vojtechsimetka**
Screenshot 2022-06-19 at 21 01 38

### CODE REVIEW

**Comment by bee-worker** [comment]
## 🐝 PR preview in Swarm

**Preview URL:** https://bah5acgzaz4omujguqmrrrqsmywvn3722dwdv52m7mlbxxnaeinssfxkbwfka.bzz.link
**Swarm Hash:** `cf1cca24d4832318c24cc5aaddff5a1d875ee99f62c37bb404436522dd41b154`
**Commit Hash:** 540534ef857f2d05700db39ff1d011ec6bc7f28c
**Commit Message:** feat: fetch and process map data DB

**Comment by AuHau** [comment]
Wait, so there will be ~300kB file containing all the Swarm's known nodes with their locations distributed for the map source? Will this be only for Desktop or also for general Dashboard functionality?

**Comment by vojtechsimetka** [comment]
> Wait, so there will be ~300kB file containing all the Swarm's known nodes with their locations distributed for the map source? Will this be only for Desktop or also for general Dashboard functionality?

Yes. Until we get IP or location data from Bee :/.

We talked about this and this is the easiest solution. We will also add two more libraries that can detect your own IP address and another one to deduce location from it (https://www.npmjs.com/package/fast-geoip). Although this part I am not super sure about yet and would like to discuss again - I don't think it adds too much value for this cost.

But to answer your question. Size is not too much of a concern here. Most users will use bee-dashboard bundled in bee-desktop, swarm-extension or direct global npm install. Those who will access it from a website are still likely on a good connection as they run their own node and are likely on computer (bee-dashboard is not really usable on mobile). I understand your comment and I align with it, but I think we are reasonable here.

**Comment by AuHau** [comment]
Alright, you convinced me 😆 But yeah, lets try to get Bee to expose the peer's addresses...

**Review by Cafe137 — APPROVED** [review]

**Pull request merged**
